from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.implicitly_wait(30)
# driver.get("http://135.64.22.33:18082/ordercenter")
# driver.add_cookie({'secure': False, 'httpOnly': True, 'name': 'O2O_ORDER_JSESSIONID', 'path': '/ordercenter', 'domain': '135.64.22.33', 'value': 'c0735199-cd50-41cf-91d8-2b6bf969db0f'})
# driver.get("http://135.64.22.33:18082/ordercenter")
# driver.refresh()

driver.get("http://135.64.22.33:18082/ordercenter/loginController/login")
driver.implicitly_wait(20)
driver.find_element_by_id("usernameInput").send_keys("admin")
driver.find_element_by_id("passwordInput").send_keys("1qaz2wsx")
driver.find_element_by_id("loginButton").click()
driver.find_element_by_xpath("/html/body/div[3]/div/div/div[2]/div[1]/div[1]").click()
time.sleep(1)
driver.find_element_by_link_text("竣工回访").click()
time.sleep(2)
# driver.find_element_by_id('TITLE_HOME_PAGE').click()
# time.sleep(1)
# driver.find_element_by_xpath('/html/body/div[3]/div/div/div[1]').click()
# driver.find_element_by_id('TITLE_HOME_PAGE').click()
# driver.find_element_by_xpath('/html/body/div[5]/div/div/div[1]/div[3]/ul/li[2]/a[1]').click()
# driver.quit()
driver.switch_to.frame(1)
driver.find_element_by_link_text("订单处理").click()
# driver.find_element_by_link_text("订单处理").click()
time.sleep(3)
driver.switch_to.parent_frame() #last frame
# driver.switch_to.default_content() #home frame
driver.switch_to.frame(2)
driver.find_element_by_xpath('/html/body/div[16]/div[2]/div[2]/div[10]/button[1]').click()
driver.find_element_by_xpath('/html/body/div[23]/div[3]/a[1]/span').click()
time.sleep(2)
driver.quit()
